server:
  port: 8071
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devraghavm/microservices-config-server-repository
          username: devraghavm
          password: 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
          default-label: main
          clone-on-start: true
      fail-fast: true
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411/
#    sender:
#      type: rabbit
#    rabbitmq:
#      queue: zipkin
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

encrypt:
  key: eazybytes